worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Shared Proxy Configuration
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;

    # SSL Configuration
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Frontend (Static assets / Next.js)
        location / {
            proxy_pass http://fe:3000;
        }

        # Backend API (Forward to Kong)
        location /api {
            proxy_pass http://kong:8000;
        }

        # Swagger UI
        location /swagger-ui/ {
            proxy_pass http://swagger-ui:8080/;
        }

        location = /api-docs {
            return 301 $scheme://$http_host$uri/;
        }

        location /api-docs/ {
            proxy_pass http://swagger-ui:8080/;
        }

#        # Monitoring / Prometheus
#        location /metrics {
#            proxy_pass http://prometheus:9090;
#        }
    }

    # Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }
}
