server:
  port: 8080

spring:
  application:
    name: shopping-cart-service
  datasource:
    url: ${CART_DB_URL:jdbc:postgresql://postgres:5432/cart_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
